#!/bin/zsh

python3 -m venv venv
source venv/bin/activate
pip install pip --upgrade
pip install fonttools

echo patching bold variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-bold-nerd-font-translated.ttf "fixed" "hc" "bold" "3.1.1" "1.0.0"
echo patching bolditalic variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-bolditalic-nerd-font-translated.ttf "fixed" "hc" "bolditalic" "3.1.1" "1.0.0"
echo patching extralight variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-extralight-nerd-font-translated.ttf "fixed" "hc" "extralight" "3.1.1" "1.0.0"
echo patching extralightitalic variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-extralightitalic-nerd-font-translated.ttf "fixed" "hc" "extralightitalic" "3.1.1" "1.0.0"
echo patching italic variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-italic-nerd-font-translated.ttf "fixed" "hc" "italic" "3.1.1" "1.0.0"
echo patching light variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-light-nerd-font-translated.ttf "fixed" "hc" "light" "3.1.1" "1.0.0"
echo patching lightitalic variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-lightitalic-nerd-font-translated.ttf "fixed" "hc" "lightitalic" "3.1.1" "1.0.0"
echo patching regular variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-regular-nerd-font-translated.ttf "fixed" "hc" "regular" "3.1.1" "1.0.0"
echo patching semibold variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-semibold-nerd-font-translated.ttf "fixed" "hc" "semibold" "3.1.1" "1.0.0"
echo patching semibolditalic variant...
python3 patch-ttf-name-for-sarasa-nerd.py sarasa-fixed-hc-semibolditalic-nerd-font-translated.ttf "fixed" "hc" "semibolditalic" "3.1.1" "1.0.0"
echo finished
deactivate
